.travis.yml, cev_eris.dme, code/game/machinery/autodoc.dm, code/game/objects/items/weapons/circuitboards/machinery/medical.dm
Add the `code\game\machinery\autodoc.dm` to the .dme to include the autodoc machinery.
It's requested by the community.
:cl:
add: Add the autodoc machinery
/:cl:
=> Include autodoc machinery to the game

.github/workflows/compile_changelogs.yml, .github/workflows/make_changelogs.yml
:cl:
config: Automatic changelog generation has been enabled for SyzygyStation/Syzygy-Eris
/:cl:
=> Enable Automatic CL generation

code/datums/outfits/jobs/medical.dm, code/game/jobs/job/medical.dm
Renames the job name and its outfit set from `Chemist` to `Pharmacist`
Requested by community.
```changelog
tweak: Renamed "Chemist" to "Pharmacist"
```
=> Renames Chemist job to Pharmacist

code/modules/tips_and_tricks/jobs.dm
Work in progress - This pull is to fix some discrepancies in the tips that are holdovers from Eris.
Having lore-accurate tips is always nice for newbies to the server.
Closes https://github.com/SyzygyStation/Syzygy-Eris/issues/31
```changelog
tweak: Added and removed some tips, tweaked others to better fit our lore.
spellcheck: Corrected the spelling of some other tips.
```
=> Adjusts in-game tips to fit our lore.

code/game/jobs/whitelist.dm, code/game/verbs/ooc.dm
Replaced two mentions of the Eclipse Discord with a link to the forums. 
Links to a better place for whitelisting.
```changelog
fix: Replaced inks to the Eclipse Discord with the Syzygy Forum. 
```
=> Replaced mentions of Eclipse Discord.

code/modules/organs/internal/carrion.dm
fixes russian typos and adds message while laying down carrion spider next
russian grammar man bad, also it was weird that laying down nests did not have a message.
```changelog
add: message while laying down carrion spider next
spellcheck: fixed a few carrion typos
```
=> Carrion grammar changes

code/game/machinery/vending.dm, code/game/machinery/vending_eclipse.dm
Changes vendor stock and prices.
The weapon and medical vendor stock/price were cluttered and nonsensical. This fixes both of those things.
```changelog
tweak: Changed stock of Frozen Star, BulletHeaven, and medbay lobby vendors.
balance: Changed prices of products in above.
```
=> Vendors fix

code/global.dm, code/modules/economy/economy_misc.dm, code/modules/games/spaceball_cards.dm
Updated the year on the bank sheet, updated the in game year for hopefully the last time and updated the Spaceball cards
```changelog
tweak: Fixed a couple of years.
```
=> Updated in game years.

code/modules/mob/mob_grab_specials.dm
A PR meant to address https://github.com/SyzygyStation/Syzygy-Eris/issues/64
Makes the game more playable, also fixes https://github.com/SyzygyStation/Syzygy-Eris/issues/64
```changelog
add: Joint-locking is now visible to everyone in view
fix: Fixed joint-locking not showing messages when it should
```
=> Improve joint-locking feedback

maps/submaps/deepmaint_rooms/normal/oopsitsbeartraps.dmm, maps/submaps/deepmaint_rooms/normal/oopsitsphoron.dmm
adds syzygy flavor to my deepmaint rooms
flavor and lore is good. also fixed some mapping issues/tweaks sum shit about them specifically
```changelog
tweak: fixed some deepmaint rooms
```
=> adds syzygy specific flavor fixes to muh deepmaint rooms

code/modules/client/preference_setup/loadout/lists/headwear.dm, code/modules/client/preference_setup/loadout/lists/uniforms.dm
Fixed it so that the loadout items the Gunnery Sergeant should be able to take are able to be taken.
Items for the Gunnery Sergeant should be able to be taken by them in loadout.
```changelog
fix: ixed the gunnery sergeant loadout.
```
=> Fixes Gunnery Sergeant Loadout.

code/datums/objective/merc_mission.dm
specifically removes your head immediately blowing up upon loss and makes timer 900 minutes
was discussed with other staff. time limits bad for rp. more time = more rp = good
```changelog
tweak: merc timer
```
=> removes merc timer

code/game/dna/dna2.dm
As what it says on the tin, it fixes some issues related to DNA.
Should fix https://github.com/SyzygyStation/Syzygy-Eris/issues/47
Not sure about stats, as the fixes were already done to cruciforms instead. So it may apply when we finally change to NeoTheology's cruciforms and disable soulcrypts.
```changelog
fix: Fix custom species names not being cloned to DNA
fix: Fix hair and ears sharing the same DNA block
```
=> Fix some DNA shit

code/modules/biomatter_manipulation/solidifier.dm
Say what you want about cloning, but having to grind lot of materials to clone one single person in an action-oriented server is a bit too much.
Makes medical more bearable
```changelog
balance: Buffed amount biomatter per sheet from 1 to 10. 
```
=> Buff amount of biomatter per sheet

code/modules/economy/Accounts.dm
Fixed bank account creation to be more in line with our lore.
We're not in the 2500s.
```changelog
fix: fixed the account creation date.
```
=> Changed years with Bank Accounts.

code/game/jobs/job/medical.dm
Removed an Eris mention I missed in the chemist's job description.
We don't have Moebius.
```changelog
fix: Fixed a Moebius mention.
```
=> Removed some Moebius mentions I missed.

code/game/objects/items/weapons/tools/mods/mod_types.dm, code/modules/clothing/spacesuits/spacesuits.dm, code/modules/mechs/premade/combat.dm, code/modules/reagents/enricher.dm, code/modules/reagents/recipes.dm, code/modules/sprite_accessories/sprite_accessories_vr.dm, code/modules/telesci/bcrystal.dm, zzz_modular_syzygy/grenades.dm, zzz_modular_syzygy/loadout.dm, zzz_modular_syzygy/projectiles.dm
Runtimes should no longer be thrown for things that need plasma (renamed to phoron), stinger grenades should now be less lag inducing, space suits now cover hands and feet in case it affects permeability calculations, true yogapants are now available in the loadout, and a couple of ears that I forgot to add in got added in.
```changelog Toriate
add: Added true yoga pants to the loadout
add: Added Kulve Taroth horns and more
balance: Stinger grenades now behave more like frag grenades and should lag less
fix: fixed a few runtimes related to MATERIAL_PLASMA
```
=> Random bugfix and rebalance patch

code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/living_defense.dm
Makes armour actually work.
I think maybe that when people put on armour they had the illusion that it might actually protect them from attacks
```changelog
fix: Armour now actually protects you from damage.
```
=> armour actually works now pogchamp

maps/CEVEris/centcomm.dmm
adds medical area and bathroom to centcomm as well as adding NT signs
more flavor/rp space
```changelog
add: centcomm has bathroom and medical bay now
```
pics:
http://puu.sh/GtLL2/5ddf211e06.jpg
http://puu.sh/GtLL7/f938eb0285.jpg
=> adds medical bay and bathroom to centcomm.dmm

code/game/antagonist/station/marshal.dm
Reflavors Aegis Marshal to be a freelance bounty hunter.
Marshals can, at best, just be an extra Aegis officer. At worst, they can be validhunting tools.
```changelog
tweak: Aegis Marshal is now a bounty hunter.
```
=> marshals are now freelance bounty hunters

code/__HELPERS/global_lists.dm, code/modules/admin/holder2.dm, code/modules/admin/verbs/adminhelp.dm
Title. For the bounty! 
Fish wanted it
```changelog
admin: De-admins now receive adminhelps, if there are no admins online
```
Compiled and tested.
=> Adminhelps get sent to deadmins, if there are no admins online

code/modules/mob/living/carbon/carbon.dm
Handshake by targeting hand, not arm.
Fixes #29 
Immersion. Hands are hands, not arms.
=> Hands are hands, not arms

zzz_modular_syzygy/vote.dm
A _highly_ requested feature to make lowpop rounds more bearable.
```changelog
add: Added a vote to power the ship
```
=> Adds a vote to magically power the ship

zzz_modular_syzygy/code/modules/reagents/recipes.dm
simply makes aloe need irishcream rather then whiskey and cream
Corrects Aloe mixing so you can make it without doing sneaky tactics
```changelog
fix: Aloe now needs irishcream rather then whiskey and cream to make
```
=> Fixes Aloe mixing

code/game/objects/items/weapons/tools/_tools.dm, code/modules/clothing/masks/miscellaneous.dm
This PR will make bandanas show up on-mob again, and also ports an upstream PR to fix a runtime.
https://github.com/discordia-space/CEV-Eris/pull/5512
```changelog
fix: Bandanas now show up properly when worn
```
=> Random Bugfixes

code/datums/setup_option/core_implants.dm, code/modules/core_implant/cruciform/cruciform.dm, code/modules/organs/body_modifications.dm
Pretty much does what it says on the tin. Core implants and being part of the church no longer preclude you from having augmented limbs. 
Makes our code a little more consistent with how the lore seems to be going insofar as the church espousing that we're all just brains piloting meat mechs and we should be allowed to change them to suit our whims.
```Changelog
add: Some new opportunities for character development for the Church.
del: Commented out some whack ass code that keeps people from having augments.
tweak: Adjusted my local github environment so I could actually make this shit.
balance: rebalanced something
fix: Fixed... nothing, really. I didn't run into a single error the whole time. Not even during compiling.
```
=> Members of The Church can now augment their bodies.

zzz_modular_syzygy/code/game/jobs/SZdepartment.dm
Removed bank card from Mekhane Acolyte loadout
We have preachers now
Fixed some bad descriptions
```changelog
fix: banking card fixes
```
=> Oops! all bank card descriptions

code/datums/setup_option/core_implants.dm, code/game/objects/items/complicator.dm, code/game/objects/items/devices/last_shelter.dm, code/modules/core_implant/cruciform/cruciform.dm, code/modules/core_implant/cruciform/machinery/vat.dm, code/modules/core_implant/cruciform/modules.dm, code/modules/mob/living/carbon/human/death.dm, code/modules/mob/living/carbon/human/human_defines.dm
This PR ports https://github.com/Eclipse-Station/NEV-Northern-Light/pull/941.
Cruciforms can now be directly deposited into the cloning vat. In addition, mutation rates should be halved, and the mutation-reducing effect of Cruciforms has been doubled.
Furthermore, I have reverted changes to the Last Shelter so that it once again drops cruciforms, and also made a minor naming change to the vat.
```changelog Toriate
add: Ported yet another update to church cloning
```
=> More Church Updates

code/modules/reagents/reagents/nanites.dm
Fixes Trauma Control System not healing internal Organs
Clear as day bug
```changelog
fix: fixed TCS
```
=> fixed Trauma Control System nanites from not repairing internal organs
