SyzygyStation/Syzygy-Eris

code/game/gamemodes/events/grid_check.dm, code/game/gamemodes/events/infestation.dm, code/game/gamemodes/events/spacevine.dm, code/game/gamemodes/events/wallrot.dm
Revise storyevents by disabling them from being picked for normal gameplay, and altering the weight of others.
It's requested by the community. And it does enhance the gameplay, specially considered that the population is too low
:cl:
tweak: Limited creature candidates for the infestation event (now it's just mice, spiders, bats, spiders, and slimes)
balance: Disabled "spacevine" event
balance: Disabled "wallrot" event
balance: Lowered "grid_check" event weight lowered the maximum failure time from 1600 seconds down to 800 seconds for APCs. SMES' failure times are lot lower.
/:cl:
=> Revise story-events to enhance lowpop gameplay

.github/PULL_REQUEST_TEMPLATE.md, tools/changelog/generate_cl.py
It makes the changelogs more convenient to read and use instead of having those ugly emoji ruining the day for you!
It makes the PR easier to read.
```changelog
code: Auto-CL now looks for codeblocks annotated with "changelog" instead of emoji.
add: Add the autodoc machinery
tweak: Limited creature candidates for the infestation event (now it's just mice, spiders, bats, spiders, and slimes)
balance: Disabled "spacevine" event
balance: Disabled "wallrot" event
balance: Lowered "grid_check" event weight lowered the maximum failure time from 1600 seconds down to 800 seconds for APCs. SMES' failure times are lot lower.
```
=> Update Auto-CL workflow & recover lost CL

code/__HELPERS/unsorted.dm
*Hopefully* fix some missing code where values were not being copied from the original turfs in the templates, and thus would have high layering values and hide almost everything.
This will help preventing items disappearing under turfs. So they won't have to alt-click on them to examine its contents and pick them back up.
```changelog
fix: Fix a layering issue related to holodecks not copying plane values properly
```
=> Fix Holodeck plane layering issue

code/modules/mob/living/carbon/human/human_movement.dm
Ahah movement slowdown by hunger go booooom.
Community demand. And people no longer are threatened by another incessant factor hampering their ability to regenerate their well-being when hungry.
```changelog
del: Movement is no longer affected by hunger
```
=> Nuke hunger slowdown out of existence

code/modules/client/preference_setup/background/02_language.dm
Increase the `MAX_LANGUAGES` macro to 3.
Community demand. It will also help against insular IC meta-cliques in the future. Specially considered the *extremely* diverse selection of languages. 
```changelog
tweak: Language limit increased from 2 to 3
```
=> Increase overall limit of languages; 2 -> 3

code/datums/outfits/jobs/security.dm, code/game/objects/items/weapons/storage/deferred.dm, code/game/objects/structures/crates_lockers/closets/secure/security.dm, code/modules/clothing/suits/armor.dm, code/modules/stashes/stash_types/captain.dm
Greatcoats and overcoats had their parent type changed from `obj/item/clothing/suit/armor` to `obj/item/clothing/suit/storage`. A refactor necessary to add pockets/storage to them.
Greatcoats and overcoats now have pockets, how great is that?!?!
```changelog
add: Great-/overcoats now have pocket-like storage
refactor: Great-/overcoats changed from `armor` subtypes to `storage`
```
=> Change overcoats to storage subtypes

code/__DEFINES/species_languages.dm, code/datums/perks/job.dm, code/modules/mob/language/station.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/living/carbon/human/species/station/station_vr.dm
Make the codebase and languages a bit more maintainable by removing languages and macros are not being used at all.
It won't affect the game much, and it's a quality of life for character creation to make the language picking less overwhelming and confusing.
```changelog
del: Removed some unused code related to languages
del: Removed following languages that had definitions: `Birdsong` and `High Skrellian`
```
=> Clean-up unused languages and bloat

code/modules/scrap/scrap.dm
A probability check has been removed from the `hurt_hands` code of scrap piles. Having gloves *will always* protect from toxin injection.
Gameplay > realism. It's also a popular demand by the community.
```changelog
balance: Gloves now always will protect against cutting on scrap when rummaging in them
```
=> Gloves now always protect against scrap cutting

code/game/objects/items/devices/radio/encryptionkey.dm, code/game/objects/items/devices/radio/headset.dm
A requested change. Because it makes sense if you consider the fact they are in charge of making sure the AI is alright.
Requested change.
```changelog
tweak: Gave the RD's headset access to the `AI Private` channel
fix: The CMO's headset now have their own encryption key to differentiate from RD's headset.
```
=> Give Moebius RD access to AI Private channel

code/_onclick/cyborg.dm, code/modules/mob/living/silicon/robot/drone/_drone.dm
Drones now have ventcrawl. And alt-clicking is no longer blocked by a rather ill-advised flow control exclusive to all robots (cyborgs and drones).
It gives the drones more mobility. It's also a requested change.
```changelog
add: Drones (maintenance, construction, and biltzshell) now have the ability to ventcrawl.
fix: Alt-clicking for robots; including cyborgs and drones, had incorrect flow. It now will activate ventcrawl if they have the ability to.
```
=> Add ventcrawl to all drones

code/__DEFINES/mobs.dm, code/modules/mob/new_player/new_player.dm
Less waiting games and more actual action games. It also fixes the observer warning, when clicking on it from the lobby screen, always displaying "30 minutes" regardless of the actual value set in configuration.
Makes the SS13 less of a waiting game.
```changelog
balance: Ghost -> Mob spawn delay changed from 5 to 2 minutes
balance: Ghost -> Drone spawn delay changed from 10 to 3 minutes
fix: The warning displayed when clicking on lobby's Observe button now show the actual delay as set by the configuration
```
=> Adjust respawn delays & fix observer warning

code/modules/mob/living/silicon/robot/drone/_drone.dm
This buffs the ghost-spawnable drones to be able to pull larger objects like canisters (`ITEM_SIZE_HUGE`), while construction drones get to be able to pull wall griders and full-tile windows (`ITEM_SIZE_COLOSSAL`). At least according to the specifications in `code/__DEFINES/inventory_sizes.dm` 
Makes maintenance drones be able to e.g. setup the engine. A requested change.
```changelog
balance: Maintenance drones can now pull `ITEM_SIZE_HUGE` items, was `ITEM_SIZE_NORMAL`
balance: Construction drones can now pull `ITEM_SIZE_COLOSSAL` items, was `ITEM_SIZE_HUGE`
```
=> Buff drones' item pull size

code/modules/reagents/reagent_containers/hypospray.dm
Buffs autoinjectors.
Autoinjectors were basically unused, this makes them viable in niche situations over syringes.
```changelog
add: empty autoinjectors
tweak: autoinjectors now hold/mostly come with 10 units of reagents.
tweak: 'autoinjector/drugs' now displays as 'autoinjector (sedative)'
tweak: 'autoinjector/drugs' now contains sedatives
```
=> Autoinjector Alterations

code/game/jobs/job/security.dm
Add `access_brig = 2` to the Aegis Medical Specialist's list of access. Allowing them entry into the holding cells and the permabrig.
Requested by community
```changelog
fix: Aegis Medical Specialist now has access to the permabrig & holding cells
```
=> Add Brig access to Aegis Medical Specialist

code/game/objects/items/weapons/storage/boxes.dm
Adds the flare (`/obj/item/device/lighting/glowstick/flare`) to the survival boxes both the normal and the extended variant.
Requested by community.
```changelog
add: Added flare to survival boxes
```
=> Add flare to survival boxes

code/game/objects/items/weapons/storage/boxes.dm
Adds filled boxes for new autoinjectors.
They didn't exist before and need to for future mapping.
```changelog
add: boxes of tricord and empty autoinjectors
tweak: old autoinjector box name/description clarified
```
=> New autoinjector boxes

code/game/objects/structures/catwalk.dm, code/modules/lighting/lighting_atom.dm, code/modules/multiz/turf.dm
An alternative implementation of the https://github.com/discordia-space/CEV-Eris/issues/5109 fix https://github.com/discordia-space/CEV-Eris/pull/5196
Fixes https://github.com/discordia-space/CEV-Eris/issues/5109
Fixes https://github.com/SyzygyStation/Syzygy-Eris/issues/22
```changelog
fix: Atoms no longer fall through catwalks when they are spawned ontop of catwalks
fix: Catwalks no longer block falling from the z-level above them
fix: Open spaces now properly update when catwalks have been removed
```
=> Fix multi-z falling and catwalks

code/game/objects/items/weapons/handcuffs.dm, code/modules/mob/living/carbon/resist.dm
Makes handcuff timers read in seconds, floors the time at 20% of the original timer after Robustness reduction, uncomments the visible announce when attempting to put cuffs on people. Closes Eclipse-Station/NEV-Northern-Light#356
Gives players a better idea of how long handcuffs will take to remove (previously read in minutes rounded down, leading to cases with 0 minutes being common).
Prevents players with high robustness being able to instantly break out of any cuff with a timer less than their ROB in seconds.
Gives players some warning that handcuffs are being applied.
```changelog
tweak: made handcuff timers read in seconds.
balance: made handcuff resist timers floor at 0.2 of their original timer.
balance: made handcuffing attempts visible to mobs in view
```
=> Syzygy handcuff tweaks

code/controllers/master.dm
Quick bandaid fix to make the MC expose more details on what's happening to players, so they can use that cryptic information to send them to developers or someone else who know what they mean.
This would help developers to get more hands-on information and expose more of the state before they get reset.
```changelog
code: MC is now verbose and will tell players at where MC has failed and SoftReset, and what the states were.
```
=> Make MC error states & soft-resetting more verbose

code/datums/lobbyscreen.dm
Lowers the lobby music volume from 85 to 40.
Brings the volume mastering between in-game sound and the lobby screen in line, hopefully less hearing loss will occur between the two.
```changelog
tweak: reduced lobby music volume from 85 to 40
```
=> Reduces lobby music volume

code/modules/hivemind/mobs.dm
Several balance tweaks to the Hivemind bomber probes.
- Probes now only explode when attacking a mob, not on death.
- Reduces their maximum health (may need to tweak malfunction chance in a follow-up in case they die too much)
- Increases their base move_to_delay.
- Attacking makes a noise, a visible announce, and makes the probe glow ominously.
- Further increased move_to_delay when they begin an attack, to allow players to escape their janky simple animal movement.
Hivemind probes are the most dangerous hivemind mob by far. They still have the potential to do the most damage, but now they aren't as fast and players should have a better chance of being able to react to them.
```changelog
balance: reduced hivemind bomber health and speed, only explodes when attacking, gives more warning …
```
=> Syzygy - Hivemind Bomber Probe Nerf

code/modules/organs/internal/carrion.dm
Lets carrion spinettes spin a web on their tile for 2 chemicals. Will nerf amount needed later if required but I doubt it. Initially had it at 5 per web, but it ended up being way less than you'd hope.
Spiders good.
```changelog
add: Carrions can spin webs for 2 chemicals.
```
=> Carrionweb

code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm
Fix a runtime as described in https://github.com/SyzygyStation/Syzygy-Eris/issues/54 and https://github.com/SyzygyStation/Syzygy-Eris/issues/72
Makes the game a bit more stable;
- Fixes https://github.com/SyzygyStation/Syzygy-Eris/issues/54 
- Fixes https://github.com/SyzygyStation/Syzygy-Eris/issues/72
```changelog
fix: Fixed a runtime caused by saving character preferences when not in lobby
```
=> Fix preferences-related runtimes

code/_onclick/click.dm, code/_onclick/cyborg.dm, code/modules/ventcrawl/ventcrawl.dm
Removes an override of `AltClickOn` (mob function that calls `AltClick` of click target); moving the handling of vent-crawling into `AltClick` overrides of entry-points for ventcrawling.
Fixes https://github.com/SyzygyStation/Syzygy-Eris/issues/63
```changelog
fix: Fixed Alt-clicking being called twice for robot mobs; not showing users any Turf-tabs
refactor: Alt-clicking for vent-crawling is now handled by vents & scrubbers
```
=> Refactor alt-click handling of vent-crawling

code/modules/reagents/reagent_containers/food/drinks.dm
Fixes some ambiguous flow control that allows gulp-down to always succeed, when the conditions say otherwise
Fixes https://github.com/SyzygyStation/Syzygy-Eris/issues/42
```changelog
fix: Breaking the gulp-down wind-up now will splash on the mob and fail the act
```
=> Fix "gulp down" always succeeding when it should not

code/modules/power/gravitygenerator.dm
Fixes https://github.com/SyzygyStation/Syzygy-Eris/issues/56
Less clutter in the `View Runtimes` log, and makes it easier to pinpoint other problems.
```changelog
fix: Fixes gravity generator attempting to play the screen-shake effect to players sitting in lobby
```
=> Fix runtime caused by gravity generator

maps/CEVEris/_CEV_Eris.dmm
There are a leak to the space that causes minor inconvenience to the finest of all medical professionals hired on NanoTrash vessel Northern Lights.
Quality assurance that makes sure that our finest doctors doesn't get spaced out when they walk into the cloning room. Those doctors don't grow on trees, y'know.
```changelog
fix: Patched a leak to the space in the Medical cloning room
```
=> Patch a leak over medical cloning room

code/modules/mob/new_player/new_player.dm
This is NOT a fix for characters not spawning with a Cruciform. This is simply a literal bandaid that checks if a character has it selected in the character creator, then forcibly installs a cruciform on-spawn. It can be an effective stop-gap measure while we try and figure out how to actually fix the underlying problem.
```changelog Toriate
fix: Bandaid patch to make characters spawn (im)properly with Cruciforms
```
=> Bandaid Patch for Spawning Without A Cruciform

nano/templates/uplink.tmpl
As it turns out, it wasn't the character creator not saving exploitable information, it was the Uplink interface completely failing to display the information itself! With some HTML fuckery, it is now fixed. Closes #58 
```changelog Toriate
fix: Traitor Uplinks should now display Exploitable Information properly, instead of leaving a blank space.
```
=> Fixes Traitor Uplink Exploitable Information

code/game/objects/items.dm, code/game/objects/items/devices/radio/radio.dm, code/game/turfs/simulated/floor_icon.dm, code/modules/modular_computers/hardware/scanners/scanner_reagent.dm
Attempt to fix some runtimes that are caused by null values
Makes the game more sane, and the runtime log more clean
- Fixes https://github.com/SyzygyStation/Syzygy-Eris/issues/57
- Fixes https://github.com/SyzygyStation/Syzygy-Eris/issues/78
- Fixes https://github.com/SyzygyStation/Syzygy-Eris/issues/88
- Fixes https://github.com/SyzygyStation/Syzygy-Eris/issues/89
```changelog
fix: Fix a runtime related to updating icons of HUD-actions 
fix: Fix a runtime related to turf floorings when using the Holodeck
fix. Fix a runtime related to radios
fix: Fix a runtime related to reagent scanner module for hardsuits
```
=> Fix null-related runtimes

code/datums/contract.dm, code/datums/uplink/devices and tools.dm, code/modules/core_implant/cruciform/machinery/cloning.dm, code/modules/soulcrypt/base_implant.dm, code/modules/stashes/stash_types/captain.dm
A pretty salty PR.
Appeal to your emotions man. Salt Station 13 is the way of life.
```changelog
add: Stats are now stored in soulcrypts
add: Stats are transferred to new clones via the soulcrypt
del: Removed the bluespace harpoon from random loot
del: Removed the integrated bluespace harpoon from biltzshell drones
balance: Excelsior agents no longer have to find a bluespace harpoon
```
=> Soulcrypt hold stats & remove harpoons from traitors and loot pools.

code/modules/mob/living/carbon/human/species/station/station.dm
taj moved 0.5 slowdown faster than everyone else. on most codebases that is decent but not huge. here it was about 20% faster than everyone else lol
unathi also moved like 30% slower than everyone. this is b/c they both got literally copy-paste statblocks
fucking taj zoomers. also reduced taj brute/burn damage increase as compensation
```changelog
fix: fixed unathi/taj movespeed adjustments being too drastic
tweak: tweaked taj resistances by removing 33% of their damage vuln (1.10 from 1.15) to adjust for movespeed not being Near Teshari Levels
```
=> fixed taj and unathi movespeed finally ugh

cev_eris.dme, zzz_modular_syzygy/hugbox.dm
This PR reduces the damage of bats, makes agony damage damage simple mobs, and also allows biomatter sheet stacks to stack up to 300 sheets each.
The community requested it.
```changelog Toriate
tweak: Biomatter sheet stacks can now stack up to 300 sheets
balance: Bats now deal reduced damage
balance: Simplemobs now take damage from agony damage
```
=> Hugboxing, take 1 (totally not a idedplsnerf)

code/game/gamemodes/events/hivemind_invasion.dm, zzz_modular_syzygy/hugbox.dm
This PR will cause a Hivemind Core's presence and rough location to be revealed to the crew upon spawn, and also makes the Core less capable of stunlocking people.
Note that there are technically much more nerfs included in this PR, but they have been commented out. They are there only for reference on what the community has suggested so far.
```changelog Toriate
balance: Hivemind Core now has a longer cooldown between pulses, and their location will be revealed on spawn.
```
=> Minor Hivemind Nerf

code/modules/mob/living/carbon/human/update_icons.dm
Removed a redundant check in human update_icons that was interfering with a more comprehensive check in get_tail_icon that actually takes the presence of taur bits into account.
```changelog Toriate
fix: Taurs now show up properly in space suits
```
=> Make taurs show up properly in space suits

maps/CEVEris/_CEV_Eris.dmm
Quick stop-gap PR to map in a defib into medical so it doesn't have to be spawned in everytime.
```changelog Toriate
add: Added a defib cabinet to the medical office
```
=> Maps a defib cabinet into the medical office

code/modules/mob/living/carbon/human/human.dm
Added the Doctor Prefix for both CMO's and Doctors, now Medical Doctors and CMO'sll spawn with Doctor as their Prefix.
It's a nice flavor addition, and in practice. Most people just call Doctors either their last name or just Doc. 
```changelog
add: Added the Doctor Prefix for Chief Medical Officer and Medical Doctor.
```
=> Added new Prefixes.

cev_eris.dme, zzz_modular_syzygy/storytellers/mentor.dm
Adds a storyteller to emulate a traditional round of Extended while still keeping everyone on their toes. It's even more passive than Sleeper; antag roles in particular are _ten times less likely_ to happen.
Sometimes the crew just wants to sit down and roleplay for intervals longer than five minutes before the next vermintide shows up and kicks everyone in the ass. This lets that happen.
```
add: mentor storyteller
```
=> adds the Mentor storyteller

maps/submaps/dungeon_rooms/rooms/armory_secure.dmm
Cherry pick of https://github.com/discordia-space/CEV-Eris/pull/5424
```changelog Eris Contributors
admin: fixed admin issue regarding log spam
```
=> [CHERRY PICK] Removes a mob spawner from one of the One Star dungeon rooms (#5424)

code/game/objects/items/oddities.dm, code/modules/clothing/clothing.dm
Can fit old knives in your boots and old coins and cash on your ear slot to make them easier to carry around.
Because not all players carry around backpacks or have a lot of pockets as their job!
```changelog
tweak: made some oddities easier to carry
```
=> Oddity storage changes to make some easier to have on your person

code/modules/mob/living/carbon/human/species/station/station.dm
Unathi blood color was... not right, changed it to be in line with Bay. Also rebalanced stats slightly to be in line with the species stats document.
The changes to species stats were requested. This is done specifically for Unathi balance since they're kinda... really tanky.
```changelog
tweak: changed unathi blood color to normal bay orange
tweak: changed stats for unathi, specifically the resists
```
=> Slight changes to Unathi

cev_eris.dme, zzz_modular_syzygy/pouches.dm
A small little addition to add more items to the list of storable items in tubular pouch belts. All of the stuff is cylindrical in shape and mostly small size, or fitting within reason. 
A new modular folder was added that anyone can add more stuff to if need be. I only walked around the ship for an hour and added the stuff I found along the way. I'm sure I missed stuff that could also be added to the list.
It gives more of a reason to use the tubular pouch. Players complained about it being borderline useless.
```changelog
tweak: Tweaked/added to the list of objects the tubular pouch can hold.
```
=> More items for the tubular pouch to hold.

code/modules/reagents/recipes.dm
About The Pull Request
changes steady from needing carpotoxin to needing roach chems 
Needing an RNG drop that you probably won't get for chemistry is lame. Half the time, the ship does not move. There is generally no carp on 60% of rounds. Sad!
```changelog
tweak: steady receipe change
```
=> changes steady receipe

code/controllers/subsystems/ticker.dm
You now have 120 seconds instead of 60 seconds to goof around in Centcom.
```changelog
tweak: Round-end phase now lasts 120 seconds, up from 60 seconds
```
=> Doubles the duration of the round-end phase

cev_eris.dme, code/game/objects/structures/wire_splicing.dm, zzz_modular_syzygy/wire_splicing.dm
On examination of a wire splicing, the player will be added to a list of "aware mobs" for that specific splicing, which will then allow them to WALK over the splicing without stepping on it and getting electrocuted.
The code is pretty much copied and pasted over from the bear trap awareness code, modified to not include "Deployed". 
It adds a small QoL feature that gives the player more of a chance against wire splicings. Currently, a 1 tile hallway with a high level splicing is impassable without getting shocked or slowly cutting up the splicing. 
```changelog
add: Wire splicing awareness on examination.
```
=> Trap-style awareness for wire splicing.

code/modules/sanity/sanity_mob.dm
Started Edits on Sanity_mob.dm to enable Oddity perks to be applied to players during Inspiration Triggers, Local testing has confirmed perks being added, but has also confirmed the "lock" not functioning so players can add MORE perks from new oddities.
Feature that should be working now working is always generally a nice thing.
```changelog
fix: Fixed Oddity perks actually being applied during a inspiration trigger.
refactor: Changed and added to Code relevant in Sanity_mob.dm
```
=> Sanity_mob.DM edits

maps/CEVEris/_CEV_Eris.dmm
Aft cryo, Dorms, the bar, and escape hangar B now get publicly accessible AEDs. Cargo, Security, and the Bridge gets one as well.
```changelog
add: Mapped in a bunch of AED cabinets all over the ship
```
=> Maps in more AED cabinets

cev_eris.dme, zzz_modular_syzygy/storytellers/events.dm
Hivemind now needs 9 crew before spawning, and Blob needs 6.
```changelog Toriate
balance: Added a minimum crew requirement for Hivemind and Blob
```
=> Adds a minimum crew requirement for Hivemind and Blob

code/game/objects/items/weapons/melee/energy.dm
This is literally just my PR from upstream, being ported down.
https://github.com/discordia-space/CEV-Eris/pull/5485
```changelog Toriate
fix: Energy Armblade Implant should no longer delete itself a minute after first use
```
=> Makes the Energy Armblade Implant stop despawning itself (#5485)

cev_eris.dme, code/datums/movement/mob.dm, interface/skin.dmf, zzz_modular_syzygy/pixelshift.dm
Adds ability for a living mob to adjust their position within a tile on a per-pixel basis with ctrl+shift+arrowkey
Any movement of a living mob resets your pixel_x and pixel_y to the default values. Including forced movement
A relatively simple feature that allows for greater granularity in visuals for RP scenes.
There is an alteration to the macro file that is not modular. I was uncertain if a modular version of that file would work, and did not want to risk it. It is fairly easy to set your own macros or re-add the hotkeys later regardless if for some reason upstream touches those files.
```changelog
add: Added pixel shifting
```
https://cdn.discordapp.com/attachments/741775476477132810/758424376910544916/unknown.png
=> Added pixel-shifting with cntl+shift+movement keys

cev_eris.dme, code/controllers/subsystems/ticker.dm, zzz_modular_syzygy/vote.dm
This PR will make the server automatically start a crew transfer vote 4 hours into the round. It will then start one every hour after that.
In addition, this PR will make it so that players can vote for a full-on evacuation half an hour into the round, down from an hour and a half.
```changelog Toriate
add: Crew Transfer Votes! First one starts 4 hours into a round, then every hour after that.
```
=> Implements crew transfer votes

cev_eris.dme, zzz_modular_syzygy/storytellers/lookout.dm
Adds a new storyteller: The Lookout.
add: Adds The Lookout, a storyteller that will spawn antagonists and then go silent to let the crew make their own drama. Needs playtesting.
```changelog
add: Adds The Lookout, a storyteller that will spawn antagonists and then go silent to let the crew make their own drama. Needs playtesting.
```
=> new storyteller: the Lookout

cev_eris.dme, maps/CEVEris/_CEV_Eris.dmm
This PR will fix the dislodged blastdoor and closed-but-actually-open RnD shutters. In addition, a file that was forgotten from the .dme has been properly included, fixing some oddity descriptions.
```changelog Toriate
fix: Second section blastdoor is no longer dislodged from its frame and seemingly shut.
```
=> Map fixes and more!

cev_eris.dme, zzz_modular_syzygy/crates.dm
This PR adds the surplus gun parts crate, which can be ordered from cargo. It simply allows you to purchase formerly maint-only gun mods that are excessively rare.
```changelog Toriate
add: Surplus gun parts crates are now available to order from cargo!
```
=> Adds a surplus gun mods crate

code/game/machinery/vending.dm, zzz_modular_syzygy/storytellers/lookout.dm
Changes frozen star vendor messages. Also like, minorly changes lookout.dm since it's just a shitty bugfix. Basically, minor and moderate events kept spawning at the same time.
'Dead kids can't bully your children!' is the type of thing that's so edgy you can use it to fillet a fish.
De-syncs lookout event spawns.
```changelog
tweak: un-edgifies the frozen star vendors
tweak: lookout storyteller fixes.
```
=> changes frozen star vendor messages in vending.dm

cev_eris.dme, code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm, zzz_modular_syzygy/giant_spider.dm
Adds names for the three types of giant spiders- Japanese to contrast the German roaches.
~~The 'regular' spiders are Senshi, or soldier~~
~~Hunters are Hantā, or... hunter.~~
~~Nurses are Josanpu, or midwife~~
Toriate chose different names ask him what they mean
Adds more flavor. It also makes the three different spider types a little more distinct, with different names to go with their different sprites and effects.
```changelog
add: Names for the giant spiders!
```
=> Giant spider naming

cev_eris.dme, code/modules/economy/price_list.dm, html/changelog.html, zzz_modular_syzygy/code/game/jobs/SZdepartment.dm, zzz_modular_syzygy/code/modules/economy/price_list_fixed.dm
Moves the Civilian account over to the Club Manager
Adds a departmental fund to the civilian account
Increases base pay for the Union account
Adds a small wage for club workers.
Club workers simply put, can't really sustain themselves due to low population
A bit more roundstart humph for the Union
Fixed a major bug with how reagents interacted with exports.
Rebalanced ethanol prices.
```changelog
balance: added base pay for club workers
balance: increased starting union account value
balance: adjusted booze export values to be somewhat in line with prices IRL. Booze is valued between 100-400cr a bottle
fix: fixed reagent calculations for exports.
tweak: club manager now can access the civilian account
tweak: civilian account now has funds
```
=> Economy Tweaks

code/modules/client/preference_setup/loadout/lists/eyegear.dm
Aegis Medical Specialists can now have sunglasses selected in their loadout. They previously could not for reasons unknown.
```changelog Toriate
add: medspecs can now select sunglasses in the loadout
```
=> Medspec can has shades

code/game/jobs/job/church.dm, code/game/machinery/adv_med.dm
Preacher's still literally unplayable for reasons unknown and cruciform access is still broken, but this should actually make acolytes playable.
In addition, acolytes have been given the same cruciform upgrades as the preacher as compensation for preacher being literally unplayable.
Furthermore, I figured out how to make soulcrypts show up properly on medical scanners while testing these changes, so here it is, in a badly atomized PR.
Changes are non-modular, but marked properly.
```changelog Toriate
add: Soulcrypts now show up properly in medical scanner reports
add: Acolytes now get proper access on their IDs, and they also get the preacher's cruciform upgrades as compensation for preacher being unselectable
```
=> Actually gives access to acolytes and preachers, and make soulcrypts show up on medical scanners

code/controllers/configuration.dm, code/game/jobs/access_datum.dm, code/game/jobs/job/church.dm, code/game/jobs/job/civilian.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/guild.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm, code/game/objects/items/weapons/storage/storage.dm, code/global.dm, code/modules/admin/verbs/randomverbs.dm, code/modules/clothing/glasses/misc.dm, code/modules/mob/inventory/equip.dm, code/modules/mob/living/carbon/human/human_helpers.dm, code/modules/mob/living/carbon/human/inventory.dm, code/modules/modular_computers/file_system/programs/command/card.dm, code/modules/multiz/map_data.dm, code/modules/overmap/sectors.dm, code/modules/power/lighting.dm, code/modules/trade/datums/trade_stations_presets/zarya.dm, config/example/config.txt, interface/interface.dm, interface/skin.dmf, maps/CEVEris/overmap-eris.dm, maps/encounters/asteroid/asteroid.dm
This PR cherry picks the following PRs:
https://github.com/discordia-space/CEV-Eris/pull/5505
https://github.com/discordia-space/CEV-Eris/pull/5558
https://github.com/discordia-space/CEV-Eris/pull/5561
https://github.com/discordia-space/CEV-Eris/pull/5563
https://github.com/discordia-space/CEV-Eris/pull/5565
https://github.com/discordia-space/CEV-Eris/pull/5571
https://github.com/discordia-space/CEV-Eris/pull/5572
This should notably make the E hotkey less prone to bagging everything. Hopefully.
Also, all heads can now modify IDs with access for their specific department now.
EDIT: The ship now has a random starting position at the start of the round. It can start at the mining asteroids, space ruins, or space fortress.
**This requires a config change.**
```
RANDOM_START
#ASTEROID_START …
```
=> Yet Another Batch of Cherry Picked PRs for New Features, Bugfixes and QoL Improvements

cev_eris.dme, code/__DEFINES/misc.dm, code/modules/admin/verbs/adminpm.dm, code/modules/mob/say.dm, interface/interface.dm, interface/skin.dmf, zzz_modular_syzygy/multiline_me.dm
The maximum message length has been doubled from 1024 characters to 2048 characters.
In addition, pressing M will now open up a multiline /Me input box, just like Citadel's.
Furthermore, the admin PM to player textboxes are also multiline now.
Lastly, the say textbox gets a cancel button now.
Now everyone can enjoy their enterprise resource planning without being interrupted by arbitrary message length limitations!
```changelog Toriate
add: You can now press M to open up a multiline Me textbox.
tweak: Maximum message length has been doubled from 1024 characters to 2048 characters.
admin: Admin PMs to players are now a multiline textbox.
```
=> Quality of Life Improvements for Roleplayers and more

maps/CEVEris/_CEV_Eris.dmm
CRO and medical now have autopsy scanner
Telecoms, Captain and CRO now have the key to debug telecoms
RnD has a small move around, moving its wires and cells to a table were a frame was, and clearing room in the middle.
Tweaks the windows to be less anti-seeable 
Telecoms is kinda used when some antags and could be used in RP to have paperwork pushed to pull up log tracking past what they already have access to! (also debugging)
RnD now feels less, cramp and harder to work with with dealing with orders as you brake line of sight and cant talk to people as that happens
Autospy scanners are for getting again, more data on things and harm of the bodie used in RnD for them to again get data points.
Cargo space as wished by some and feedbacked on by others has been improved to be less horrable …
=> few* map changes

maps/CEVEris/_CEV_Eris.dmm
Now virology is not CMO-only, and the CMO's office and quarters will no longer require CE access to open.
```changelog
fix: CMO and virology airlock access has been fixed
```
=> Hotfix for CMO and Virology access being messed up

interface/interface.dm, interface/skin.dmf
I had mistakenly made M activate multiline Me even in non-hotkey mode. This has obvious ramifications. It is now fixed, and ctrl+F4 now works as an alternate universal activation method.
```changelog Toriate
fix: non-hotkeymode is now playable
```
=> Hotfix: Non-hotkeymode will now be playable

code/modules/clothing/masks/miscellaneous.dm, zzz_modular_syzygy/clothing.dm, zzz_modular_syzygy/sawnlevergun.dm
This PR focuses on implementing feedback from players. In particular:
1) The captain's voidsuit has now been properly blacklisted from the loot tables
2) CMO's labcoat has been blacklisted from the loot table
3) The bandanas now show ears and hair through
4) The sawn off lever action shotgun has been nerfed. It has one less shot, 20% less damage and armor penetration, and is more worthless.
Listening to the community is good.
```changelog Toriate
tweak: Captain's voidsuit and CMO's labcoat has been blacklisted from the loot tables
balance: Sawn off lever action shotgun has been nerfed further
fix: Bandana now shows ears and hair through
```
=> Feedback Implementation, Phase 1

cev_eris.dme, code/modules/scrap/oldificator.dm, zzz_modular_syzygy/code/modules/scrap/oldificator.dm
All this does is add a specific oldification for the design disks that makes the disks have a 90% chance of having anywhere between 3 and 3 less than the maximum value of LP for any old disks.
Disks in the trash shouldn't have the full amount of license points. 
```changelog
balance: Balances the old disks to not be as good as just a regular, untarnished disks, 
```
=> Randomizes the License point value for oldified disks.

code/game/objects/items/weapons/implant/implants/excelsior.dm, code/modules/core_implant/core_implant.dm
Pretty much does what it says on the tin. Core implants and being part of the church no longer preclude you from having implants of any type.. 
Makes our code a little more consistent with how the lore seems to be going insofar as the church espousing that we're all just brains piloting meat mechs and we should be allowed to change them to suit our whims. This just takes it a step further with allowing implants.
```Changelog
tweak: Core implants no longer prevent you from having additional implants. Death alarms for our custodians, weee.
=> Fixes not being able to implant implants in core implanted people with implanters.

code/modules/economy/economy_misc.dm, zzz_modular_syzygy/code/game/jobs/SZdepartment.dm
Fixes EFTPOS not displaying names for department accounts
Added account cards for department accounts
Added account cards to head of staff loadouts
Tweaked the Manager loadout to not use the bartender one. Removed the tophat from the loadout (because nobody wears it)
Heads of staff can now join us in using 21st century tech for banking and software! 
- NO LONGER will our research director need to TRUDGE DRUGENLY to the ATM to get out BASE CASH to pay for their materials! 
- NO LONGER will the club manager need to SULLY HIS HANDS when dealing with those UNCOUTH UNION THUGS. 
- NO LONGER will union techs BREAK the GLORIOUS EFTPOS when trying to use their MASTER'S ACCOUNT for deposits!
```changelog
fix: EFTPOS no longer break when inputting a department account.
add: department account …
```
=> Fixes EFTPOS not displaying names for department accounts

code/modules/projectiles/gun.dm, code/modules/projectiles/guns/energy.dm, code/modules/projectiles/guns/energy/laser.dm, code/modules/projectiles/guns/projectile.dm, code/modules/projectiles/guns/projectile/automatic/atreides.dm, code/modules/projectiles/guns/projectile/automatic/c20r.dm, code/modules/projectiles/guns/projectile/automatic/drozd.dm, code/modules/projectiles/guns/projectile/automatic/maxim.dm, code/modules/projectiles/guns/projectile/automatic/molly.dm, code/modules/projectiles/guns/projectile/automatic/sol.dm, code/modules/projectiles/guns/projectile/automatic/straylight.dm, code/modules/projectiles/guns/projectile/pistol/giskard.dm, code/modules/projectiles/guns/projectile/pistol/handmade.dm, code/modules/projectiles/guns/projectile/pistol/olivaw.dm, code/modules/projectiles/guns/projectile/pistol/paco.dm, code/modules/projectiles/guns/projectile/revolver/havelock.dm, code/modules/projectiles/guns/projectile/revolver/revolver.dm, code/modules/projectiles/guns/projectile/shotgun/regulator.dm, code/modules/projectiles/guns/projectile/sniper.dm
This PR is essentially a port of https://github.com/discordia-space/CEV-Eris/pull/4994, which we apparently missed, somehow. It mainly reduces the amount of copypasta present in guncode and makes it more object-oriented.
It fixes several bugs, including but not limited to:
1) Ergonomic grips not fitting on guns at all
2) Scopes not fitting on anything at all
3) The Giskard not counting as a projectile-firing weapon and thus being unable to install barrel mods
```changelog
fix: Gun tags have been fixed, meaning ergonomic grips and such should actually fit on guns now.
```
=> Gun Tagging Fix

zzz_modular_syzygy/code/modules/loot_spawn_blacklist.dm
Most of RnD guns are now RnD only.
RPG and Exl guns are now will not spawn if they did at all
Both Reclamer and the Cleaning sudd gun thing will not spawn if they did at all
hyper cells are now much rarer as well as the XL line
Both nuke disk and warez disk are now strange console only
most deferred crates will now not spawn if they did at all
AMR will no longer spawn randomly if it did at all
captain gun will no longer spawn in maints if they did at all
Preventing OP/bad things from spawning is good
```changelog
balance: Most of RnD guns are now RnD only.
balance: RPG and Exl guns are now blacklisted
balance: Both Reclamer and the Cleaning sudd gun thing
balance: hyper cells are now much rarer as well as the XL line
balance: Both nuke disk and warez disk are now strange console only …
```
=> Loads more blacklisting

cev_eris.dme, code/modules/reagents/reagents/other.dm, zzz_modular_syzygy/code/game/objects/effects/decals/Cleanable/humans.dm
Fixes cleaner-based reagent reactions not properly qdel cleanable decals.
Fixes generic gibs having a missing iconstate (removed gib4 from the cleanable/gibs object)
Fixes cleaner not removing cleanable decals (they were only hidden before)(proc. Could not be modularized)
Fixes a ref to a missing gib iconstate. (modular)
Bugfixes that legitimately make sanity gain/loss problematic in commonly dirtied areas. Invisible cleanable decals will tank your sanity without being well... visible.
```changelog
fix: Cleaner reactions work properly
fix: Gibs should no longer be invisible
```
=> Cleaning fixes

zzz_modular_syzygy/defib.dm
This PR ports some defib stuff from Eclipse, and also makes it so that core implants are reactivated on defib. Among the things to note:
1) Defib timers should now actually function. They no longer run off the brain, but just the mob's listed time of death.
2) Defibs will now heal 50 oxyloss on revive. Seeing as ours are explicitly AEDs designed to be used by random passerbys, this should make it much easier for people to use them without greytiding and grabbing extra inapprovaline and dexalin.
General quality of life improvements to defib usage. No more instant death upon defibbing. No more having to rely on an acolyte or admin to reactivate your cruciform.
```changelog Toriate
tweak: cruciforms now reactivated by defibs
fix: defib timers now function, no more defibbing 5 hour old …
```
=> Defibrillator Touchup Patch

cev_eris.dme, zzz_modular_syzygy/code/modules/economy/ATM.dm
Adds a quick cash option to ATMs
Emojicracy approved right-click verb option to take out cash without going through the full UI.
Requires a linked ID card present, in the machine, and the correct PIN.
```changelog
add: quick cash option on ATMs
```
=> adds quick cash option to ATM

code/game/machinery/autolathe/autolathe.dm, code/game/machinery/smelter.dm, zzz_modular_syzygy/code/modules/economy/price_list_fixed.dm
Removes ability for autolathe to eat stuff 
Buffs improved smelter from 25/30/35/40/45/50% efficiency to 25/40/55/70/85/100% efficiency 
Fewer mats from maint. Less access to rare mats outside of cargo. More reasons for sci to upgrade cargo. Less proliferation of high-end printed equipment.
It's a painful change, but a really necessary one. Autolathes should not be better at recycling than a dedicated smelter.
This also encourages people to go to cargo with scrap rather than hoarding it.
```changelog
balance: autolathes can no longer recycle anything at 100% efficiency
balance: buffed smelter recycling rate when upgraded from 5% per tier to 15% per tier.
```
...
I am sorry.
=> Nerfed Autolathe recycling

zzz_modular_syzygy/code/modules/economy/price_list_fixed.dm
Fixed tools exporting for 30x their material costs.
Fixed ammo casings exporting for 20cr a pop.
Makes tools and ammo slightly less stupidly profitable when exporting.
```changelog
tweak: adjusted ammo and tool prices.
```
=> pricing adjustments

code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/human/species/station/monkey.dm, code/modules/sanity/sanity_mob.dm
This PR cherry picks https://github.com/discordia-space/CEV-Eris/pull/5635, which makes monkeys stop processing environmental sanity factors and drastically reduces the amount of resources they hog up, which should make the server run better. _In theory_.
I've compiled it successfully and it doesn't throw any runtimes when tested, but I don't have enough COG to interpret the profiler results to tell how good the optimizations are.
Optimizations good.
```changelog CEV-Eris Developers
tweak: NPC monkeys don't receive environment sanity damage and insight.
code: onLife() sanity procs effects trigger once every 2 life ticks.
```
=> Cherry picks an optimization PR from upstream

code/game/atoms.dm, code/game/objects/items/weapons/grenades/grenade.dm, code/modules/biomatter_manipulation/bioreactor/platform.dm, code/modules/economy/cash.dm, code/modules/economy/price_list.dm, code/modules/mechs/mech_interaction.dm, code/modules/mechs/mech_life.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/carbon_defines.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/life.dm, code/modules/mob/mob_defines.dm, code/modules/mob/mob_helpers.dm, code/modules/multiz/structures.dm, code/modules/multiz/turf.dm, code/modules/power/cell.dm, code/modules/projectiles/guns/energy/nt_svalinn.dm, code/modules/projectiles/guns/energy/plasma.dm, code/modules/projectiles/guns/projectile/pistol/colt.dm, code/modules/projectiles/guns/projectile/pistol/mk58.dm, code/modules/projectiles/guns/projectile/pistol/paco.dm
Ports the following PRs from upstream:
https://github.com/discordia-space/CEV-Eris/pull/5473
https://github.com/discordia-space/CEV-Eris/pull/5474
https://github.com/discordia-space/CEV-Eris/pull/5524
https://github.com/discordia-space/CEV-Eris/pull/5531
https://github.com/discordia-space/CEV-Eris/pull/5613
https://github.com/discordia-space/CEV-Eris/pull/5612
https://github.com/discordia-space/CEV-Eris/pull/5611
https://github.com/discordia-space/CEV-Eris/pull/5608
https://github.com/discordia-space/CEV-Eris/pull/5624
Important notes:
- No more money duping!
- Ladder peeking and ladder fragging!
- Mech sensors actually work now!
- Throwing cigarettes and crayons at helmeted people a floor below you no longer stuns them!
- High MEC individuals can now determine if a cell is rigged and …
=> Fixes Galore!

code/game/machinery/pipe/pipe_dispenser.dm, code/modules/tables/tables.dm, zzz_modular_syzygy/code/modules/economy/price_list_fixed.dm
t## About The Pull Request
Fixed UI on Pipe dispensers, disposal dispensers
Fixes custom appearance tables from being moved. Apply crowbar to remove the carpet.
Bug fixes
```changelog
fix: fixed pipe dispenser UI
fix: fixed disposal dispenser UI
fix: fixed custom tables being unable to be deconstructed
```
This needs to be merged AFTER the price fix PR. I apologize for the sloppy git trail.
=> Pipe Dispeser, Disposal Dispenser, and Bar table fixes

code/game/jobs/job/church.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/guild.dm, code/game/jobs/job/security.dm, zzz_modular_syzygy/defib.dm
This PR will set the defib timer back to 15 minutes, as well as fix the glaring issue with dysfunctional roundstart spawnpoint landmarks. Engineers most notably get to spawn properly again.
Closes #236 
```changelog Toriate
tweak: Defib timer is now 15 minutes again, as it was
fix: Roundstart spawnpoints should now function again, instead of randomly dumping you in maintenance
```
=> Defib Timer Tweaks, Spawnpoint Bugfixes
